#!/bin/bash

# Program to output a system information page

echo "<HTML>"
echo "	<HEAD>"
echo "		<TITILE>Page Title</TITLE>"
echo "	</HEAD>"
echo "	<BODY>"
echo "			Page body"
echo "	</BODY>"
echo "</HTML>"
echo "
"
